import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, Check, Code2, Command, Copy, Download, FolderOpen, LayoutDashboard, Play, RotateCcw, Search, Settings, Square, Terminal, X } from 'lucide-react';
import './styles.css';
const agents=[{name:'Codex',model:'default',color:'#84f1bf'},{name:'Ollama',model:'qwen3',color:'#d5d8df'},{name:'Claude Code',model:'coming soon',color:'#e8aa79'},{name:'Gemini CLI',model:'coming soon',color:'#8ab4f8'}];
const demos=[{id:'demo-1',title:'Refactor authentication flow',agent:'Codex',time:'demo',state:'Demo',output:'This is an example. Start Codex or Ollama to receive real output.',logs:'No terminal messages.',files:''},{id:'demo-2',title:'Explain this repository',agent:'Ollama',time:'demo',state:'Demo',output:'Select Ollama, enter a task, then click Run task.',logs:'No terminal messages.',files:''}];
function App(){
 const [agent,setAgent]=useState(agents[0]),[prompt,setPrompt]=useState(''),[running,setRunning]=useState(false),[runs,setRuns]=useState(()=>JSON.parse(localStorage.getItem('agentdock-runs-v2')||'null')||demos),[detail,setDetail]=useState(null),[path,setPath]=useState(()=>localStorage.getItem('agentdock-project')||''),[health,setHealth]=useState({}),[aborter,setAborter]=useState(null);
 useEffect(()=>localStorage.setItem('agentdock-runs-v2',JSON.stringify(runs)),[runs]);useEffect(()=>localStorage.setItem('agentdock-project',path),[path]);useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setHealth({}))},[]);
 const connected=agent.name==='Codex'?health.codex:agent.name==='Ollama'?health.ollama:false;
 const update=(id,fn)=>{setRuns(old=>old.map(r=>r.id===id?fn(r):r));setDetail(old=>old?.id===id?fn(old):old)};
 async function runTask(retry){const text=typeof retry==='string'?retry:prompt.trim();if(!text||running)return;const run={id:crypto.randomUUID(),title:text,agent:agent.name,model:agent.model,time:'now',state:'Running',output:'',logs:'',files:'',serverId:''};setRuns(old=>[run,...old]);setDetail(run);setPrompt('');setRunning(true);const ac=new AbortController();setAborter(ac);try{const response=await fetch('/api/run',{method:'POST',signal:ac.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:agent.name,model:agent.model,prompt:text,projectPath:path})});if(!response.ok)throw new Error((await response.json()).error||'Run failed.');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const e=JSON.parse(line);update(run.id,r=>{const n={...r};if(e.id)n.serverId=e.id;if(e.type==='output')n.output+=e.text;if(e.type==='log')n.logs+=e.text;if(e.type==='files')n.files=e.text;if(e.type==='done')n.state='Completed';if(e.type==='error'){n.state='Failed';n.logs+=`\n${e.text}`}return n})}}}catch(e){update(run.id,r=>({...r,state:e.name==='AbortError'?'Stopped':'Failed',logs:r.logs+`\n${e.name==='AbortError'?'Run stopped.':e.message}`}))}finally{setRunning(false);setAborter(null)}}
 function stop(){aborter?.abort();if(detail?.serverId)fetch(`/api/stop/${detail.serverId}`,{method:'POST'}).catch(()=>{});setRunning(false)}
 function exportRun(){if(!detail)return;const body=`# ${detail.title}\n\nAgent: ${detail.agent}\nStatus: ${detail.state}\n\n## Output\n${detail.output}\n\n## Logs\n${detail.logs}\n\n## Changed files\n${detail.files}`;const url=URL.createObjectURL(new Blob([body],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='agentdock-run.md';a.click();URL.revokeObjectURL(url)}
 return <div className="shell"><aside><div className="logo"><div className="logoMark"><Command size={17}/></div><span>AgentDock</span><b>local</b></div><nav><button className="active"><LayoutDashboard size={17}/><span>Workspace</span></button><button><Bot size={17}/><span>Agents</span></button><button><Terminal size={17}/><span>Runs</span></button><button><Settings size={17}/><span>Settings</span></button></nav><div className="spacer"/><div className="safety"><i/> Local API<br/><span>127.0.0.1 only</span></div><a className="repoLink" href="https://github.com/TasarikOfficial/AgentDock"><Code2 size={16}/> GitHub repository</a></aside><main><header><div><span className="eyebrow">LOCAL AGENT WORKSPACE</span><h1>Command center</h1></div><div className="search"><Search size={15}/> Runs and agents</div><a className="iconBtn" href="https://github.com/TasarikOfficial/AgentDock"><Code2 size={19}/></a></header>
 <section className="hero"><div><span className="live"><i/> LOCAL-FIRST</span><h2>Give the task.<br/><em>Watch the work.</em></h2><p>Run Codex on a project or chat with your local Ollama model. Output streams here in real time.</p></div><div className="orb"><div className="orbit o1"><i/></div><div className="orbit o2"><i/></div><div className="core"><Command size={27}/></div></div></section>
 <section className="composer"><div className="selectAgent"><span className="agentDot" style={{background:agent.color}}/><select value={agent.name} onChange={e=>setAgent(agents.find(a=>a.name===e.target.value))}>{agents.map(a=><option key={a.name}>{a.name}</option>)}</select><span className="model">{agent.model}</span><span className={`connection ${connected?'online':''}`}>{connected?'Connected':'Not detected'}</span></div>{agent.name==='Codex'&&<label className="projectPath"><FolderOpen size={15}/><input value={path} onChange={e=>setPath(e.target.value)} placeholder="/Users/your-name/Desktop/project"/></label>}<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')runTask()}} placeholder="Describe the task…"/><div className="composeBottom"><span>Real local output · no API key stored</span><button className="run" disabled={!prompt.trim()||running} onClick={()=>runTask()}>{running?<Activity className="spin" size={16}/>:<Play size={15}/>} {running?'Running…':'Run task'} <kbd>⌘↵</kbd></button></div></section>
 <div className="sectionHead"><div><h3>Connected agents</h3><span>{Object.values(health).filter(Boolean).length} detected</span></div><button onClick={()=>fetch('/api/health').then(r=>r.json()).then(setHealth)}>Refresh</button></div><section className="agentGrid">{agents.map(a=>{const ok=a.name==='Codex'?health.codex:a.name==='Ollama'?health.ollama:false;return <article className={agent.name===a.name?'selected':''} onClick={()=>setAgent(a)} key={a.name}><div className="agentIcon" style={{'--agent':a.color}}><Bot size={20}/></div><div><h4>{a.name}</h4><p>{a.model}</p></div><span className="status"><i style={{background:ok?'#72dd9e':'#59616a'}}/>{ok?'Ready':'Offline'}</span></article>})}</section>
 <div className="sectionHead"><div><h3>Runs</h3><span>Click any run to inspect output</span></div><button onClick={()=>setRuns(demos)}>Reset demo</button></div><section className="runs">{runs.slice(0,8).map(r=><div className="runRow" onClick={()=>setDetail(r)} key={r.id}><div className="runGlyph">{r.state==='Completed'?<Check size={16}/>:<Activity className={r.state==='Running'?'spin':''} size={16}/>}</div><div className="runTitle"><strong>{r.title}</strong><span>{r.agent} · {r.time}</span></div><span className={`pill ${r.state.toLowerCase()}`}>{r.state}</span></div>)}</section></main>
 {detail&&<section className="runDrawer"><div className="drawerHead"><div><span>RUN DETAILS</span><h3>{detail.title}</h3><p>{detail.agent} · {detail.state}</p></div><button onClick={()=>setDetail(null)}><X size={19}/></button></div><div className="drawerActions">{detail.state==='Running'?<button onClick={stop}><Square size={14}/> Stop</button>:<button onClick={()=>{setAgent(agents.find(a=>a.name===detail.agent)||agents[0]);runTask(detail.title)}}><RotateCcw size={14}/> Run again</button>}<button onClick={()=>navigator.clipboard.writeText(detail.output||detail.logs)}><Copy size={14}/> Copy</button><button onClick={exportRun}><Download size={14}/> Export</button></div><h5>OUTPUT</h5><pre className="agentOutput">{detail.output||(detail.state==='Running'?'Waiting for output…':'No response text.')}</pre>{detail.files&&<><h5>CHANGED FILES</h5><pre className="fileOutput">{detail.files}</pre></>}<h5>TERMINAL LOG</h5><pre className="terminalOutput">{detail.logs||'No terminal messages.'}</pre></section>}</div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
